### ISSUE TITLE
Cannot add new contributions

### ISSUE THREAD

**Issue by dexpota** [all-contributors/all-contributors-cli#209] opened 2019-10-07 06:45 UTC
- `all-contributors-cli` version: 6.9.1
- `node` version: 12.6.0
- `npm` version: 6.11.3

You can find the configuration file [here](https://github.com/dexpota/kitty-themes/blob/master/.all-contributorsrc)

If I run `all-contributors` from the project's root directory and select to add a new contribution I get this error:

```
is/are invalid contribution type(s)
```

This issue is not present if I run `all-contributors` version `6.9.0`

**Comment by Berkmann18** [comment] 2019-10-07 09:39
@dexpota What exactly have you typed?

**Comment by dexpota** [comment] 2019-10-07 09:45
I typed `all-contributors` on the shell then I selected `Add new contributor ...` and it gives me that message.

**Comment by Berkmann18** [comment] 2019-10-07 13:58
It seems like I get that error as well, I'm unable to look into it now but will do asap.

**Comment by Berkmann18** [comment] 2019-10-11 17:10
I've looked into it and can see why this happens but I'm unsure when that bug was introduced and I'm really busy at the moment so I can't seem to find what recent change caused this (especially since `git blame` points to fairly old contributions on the relevant LOCs).

Have you tried to reproduce this error with previous version?

**Comment by dexpota** [comment] 2019-10-12 22:05
The version `6.9.0` seems to work just fine.

**Comment by dexpota** [comment] 2019-10-16 12:04
I could look into this issue. This would be the first contribution for me on this project, do you think is it a good first-timer issue?

**Comment by Berkmann18** [comment] 2019-10-16 18:26
That would be amazing and welcome... And that goes in line with the other first-timer issues across AC repos.

So go ahead when you can :grinning:.

**Comment by Berkmann18** [comment] 2021-03-23 10:57
Just noticed this wasn't closed and yet fixed so closing this.

**Closed by Berkmann18** 2021-03-23 10:57 UTC
Labels: bug, status: available
